

FIRMS = {

"Apple Inc.": "AAPL",
"Abbott Laboratories": "ABT",
"Aflac Inc.": "AFL",
"Akamai Technologies, Inc.": "AKAM",
"Advanced Micro Devices, Inc.": "AMD",
"Amgen Inc.": "AMGN",
"Amazon.com, Inc.": "AMZN",
"American Airlines": "AAL",
"Ametek Inc": "AME",
"Abiomed Inc": "ABMD",
"Apartment Investment and Management Company": "AIV",
"Assurant, Inc.": "AIZ",
"Allegion plc": "ALLE",
"Amcor": "AMCR",
"Etsy": "Etsy",
"Apt PLC": "APTV",
"Atmos Energy Corporation": "ATO",
"AvalonBay Communities, Inc.": "AVB",
"Baker Hughes Company": "BKR",
"Aon plc": "AON",
"Activision Blizzard, Inc.": "ATVI",
"Booking Holdings Inc.": "BKNG",
"BlackRock, Inc.": "BLK",
"Boston Scientific Corporation": "BSX",
"Caterpillar Inc.": "CAT",
"Chubb Limited": "CB",
"Cboe Global Markets, Inc.": "CBOE",
"Carnival Corporation": "CCL",
"Cadence Design Systems, Inc.": "CDNS",
"Cigna Corporation": "CI",
"AES Corp": "AES",
"Albemarle Corporation": "ALB",
"APA Corporation": "APA",
"Apache Corporation": "APA",
"Alexandria Real Estate Equities, Inc.": "ARE",
"Adobe": "ADBE",
"Oracle": "ORCL",
"Etsy": "Etsy",
"Boeing": "Boeing",
"Paycom": "Paycom",
"Starbucks": "Starbucks",
"Syros Pharmaceuatical": "SYRS",
"Wingstop": "WING",
"Cummins Inc.": "CMI",
"ConocoPhillips": "COP",
"Costco Wholesale Corporation": "COST",
"Campbell Soup Company": "CPB",
"Cisco Systems, Inc.": "CSCO",
"CVS Health Corporation": "CVS",
"Lockheed Martin Corporation": "LMT",
"Mastercard Incorporated": "MA",
"Marriott International, Inc.": "MAR",
"Mattel, Inc.": "MAT",
"Microchip Technology Incorporated": "MCHP",
"MGM Resorts International": "MGM",
"Monster Beverage Corporation": "MNST",
"Morgan Stanley": "MS",
"Microsoft Corporation": "MSFT",
"M&T Bank Corporation": "MTB",
"Netflix, Inc.": "NFLX",
"AT&T Inc.": "T"

}
